### ISSUE TITLE
Compatibility with Microsoft Language Server Protocol

### ISSUE THREAD

**Issue by goyalyashpal** [samuong/octave-langserver#3]
is this language server for octave compatible with Microsoft LSP?

https://microsoft.github.io/language-server-protocol/

[*]: https://github.com/search?q=octave+language+server

**Comment by samuong** [comment]
Hi @yashpalgoyal1304, I hope it will be one day, but right now this is very early days and very little functionality has been implemented. I might update some of the docs to make that clearer at some point.
